# .goreleaser.yaml
project_name: vfox
before:
  hooks:
    - go mod tidy
builds:
  - binary: 'vfox'
    main: './cmd'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: '^feat:'
      order: 100
    - title: "Bug fixes"
      regexp: '^fix:'
      order: 200
    - title: "Documentation updates"
      regexp: '^doc:'
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

brews:
  - name: 'vfox'
    repository:
      owner: version-fox
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    folder: Formula
    goarm: "7"
    homepage: https://github.com/version-fox/vfox
    description: A cross-platform SDK version manager with a simple cli.
    url_template: "https://github.com/version-fox/vfox/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license: "Apache-2.0"
    commit_author:
      name: "Han Li"
      email: aooohan@gmail.com
    #    dependencies:
    #      - name: go
    #        type: optional
    #      - name: git
    test: |
      system "#{bin}/vfox version"

nfpms:
  - file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    id: vfox
    homepage: https://github.com/version-fox/vfox
    description: |-
      A cross-platform SDK version manager with a simple cli.
      Swiftly install and switch between different SDK versions 
      using Lua scripts as plugins. Simplify your version management 
      with VersionFox.
    maintainer: Han Li <aooohan@gmail.com>
    license: 'Apache-2.0'
    vendor: VersionFox
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/vfox/copyright
        file_info:
          mode: 0644
    formats:
      - rpm
      - apk
      - deb
    rpm:
      group: Development/Tools

#winget:
#  - name: vfox
#    publisher: lihan
#    license: 'Apache-2.0'
#    homepage: https://github.com/version-fox/vfox
#    short_description: A cross-platform SDK version manager with a simple cli.
#    repository:
#      owner: aooohan
#      name: vfox-winget-pkgs
#      branch: "vfox-{{.Version}}"
#      pull_request:
#        enabled: true
#        draft: true
#        base:
#          owner: microsoft
#          name: winget-pkgs
#          branch: master
sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

release:
  draft: false
  prerelease: true
  name_template: "v{{ .Version }}"
  footer: |
    **Full Changelog**: https://github.com/version-fox/vfox/compare/{{ .PreviousTag }}...{{ .Tag }}