# .goreleaser.yaml
project_name: vfox
before:
  hooks:
    - go mod tidy
builds:
  - binary: 'vfox'
    main: './'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - loong64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: loong64
      - goos: darwin
        goarch: loong64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser -X main.treeState={{ .IsGitDirty }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "ðŸš€ New Features"
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: "ðŸ› Bug Fixes"
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: "ðŸ“ Documentation"
      regexp: '^docs?(\(.+\))?:'
      order: 2
    - title: "âš¡ Performance Improvements"
      regexp: '^perf(\(.+\))?:'
      order: 3
    - title: "â™»ï¸ Refactoring"
      regexp: '^refactor(\(.+\))?:'
      order: 4
    - title: "ðŸŽ¨ Styling"
      regexp: '^style(\(.+\))?:'
      order: 5
    - title: "ðŸ§ª Tests"
      regexp: '^test(\(.+\))?:'
      order: 6
    - title: "ðŸ”§ Chores"
      regexp: '^chore(\(.+\))?:'
      order: 7
    - title: "ðŸ“¦ Build & CI"
      regexp: '^(build|ci)(\(.+\))?:'
      order: 8
    - title: "â¬†ï¸ Dependencies"
      regexp: '^(deps|dep)(\(.+\))?:'
      order: 9
    - title: "Other Changes"
      order: 999

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*

brews:
  - name: 'vfox'
    repository:
      owner: version-fox
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    folder: Formula
    goarm: "7"
    homepage: https://github.com/version-fox/vfox
    description: A cross-platform SDK version manager with a simple cli.
    url_template: "https://github.com/version-fox/vfox/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license: "Apache-2.0"
    commit_author:
      name: "Han Li"
      email: aooohan@gmail.com
    test: |
      system "#{bin}/vfox version"
    extra_install: |-
      bash_completion.install "completions/bash_autocomplete" => "vfox"
      zsh_completion.install "completions/zsh_autocomplete" => "_vfox"

nfpms:
  - file_name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    id: vfox
    homepage: https://github.com/version-fox/vfox
    description: |-
      A cross-platform SDK version manager with a simple cli.
      Swiftly install and switch between different SDK versions 
      using Lua scripts as plugins. Simplify your version management 
      with VersionFox.
    maintainer: Han Li <aooohan@gmail.com>
    license: 'Apache-2.0'
    vendor: VersionFox
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/bash_autocomplete
        dst: /usr/share/bash-completion/completions/vfox
        file_info:
          mode: 0644
      - src: ./completions/zsh_autocomplete
        dst: /usr/share/zsh/site-functions/_vfox
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/vfox/copyright
        file_info:
          mode: 0644
    formats:
      - rpm
      - deb
    rpm:
      group: Development/Tools

#winget:
#  - name: vfox
#    publisher: lihan
#    license: 'Apache-2.0'
#    homepage: https://github.com/version-fox/vfox
#    short_description: A cross-platform SDK version manager with a simple cli.
#    repository:
#      owner: aooohan
#      name: vfox-winget-pkgs
#      branch: "vfox-{{.Version}}"
#      pull_request:
#        enabled: true
#        draft: true
#        base:
#          owner: microsoft
#          name: winget-pkgs
#          branch: master

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

release:
  draft: true
  prerelease: auto
  name_template: "v{{ .Version }}"
  replace: false
  header: |
    ## ðŸŽ‰ What's Changed in v{{ .Version }}
    
  footer: |
    
    ---
    **Full Changelog**: https://github.com/version-fox/vfox/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## Installation
    
    See [installation guide](https://vfox.dev/guides/quick-start.html) for more details.
    
    ## Thanks
    
    Thanks to all contributors who made this release possible! ðŸŽ‰
