proxy:
  enable: false
  url: http://test

storage:
  sdkPath: /tmp

registry:
  address: "https://cdn.jsdelivr.net/gh/version-fox/vfox-plugins/plugins"

legacyVersionFile:
  enable: true

cache:
  availableHookDuration: -1