package shell

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/version-fox/vfox/internal/env"
)

type nushell struct{}

var Nushell = nushell{}

const nushellConfig = `
# This script is automatically generated by vfox. It takes care of environment setup in Nushell.

# Make sure this script file is up to date when opening a new shell.
^'{{.SelfPath}}' activate nushell $nu.default-config-dir | ignore

export-env {
  # This function updates environment variables based on the output of the "vfox env" command.
  def --env updateVfoxEnvironment [] {
    {{if .EnablePidCheck}}
    # Check if PID changed (e.g., in tmux new pane)
    if ($nu.pid != $env.__VFOX_PID) {
      $env.__VFOX_PID = $nu.pid
    }
    {{end}}
    let envData = (^'{{.SelfPath}}' env -s nushell --full | from json)
    if ($envData | is-empty) {
      return
    }
    load-env $envData.envsToSet
    hide-env ...$envData.envsToUnset
  }

  # Add a pre_prompt hook that calls the above "updateVfoxEnvironment" function.
  $env.config = ($env.config | upsert hooks.pre_prompt {
    let currentValue = ($env.config | get -i hooks.pre_prompt)
    if $currentValue == null {
      [{updateVfoxEnvironment}]
    } else {
      $currentValue | append {updateVfoxEnvironment}
    }
  })

  # Tell vfox we're using Nushell and give it the current process ID.
  $env.__VFOX_SHELL = 'nushell'
  $env.__VFOX_PID = $nu.pid

  # Have vfox clean up old temp files.
  ^'{{.SelfPath}}' env --cleanup | ignore

  # Perform an initial update of the environment variables.
  updateVfoxEnvironment
}
`

// Activate implements shell.Activate by:
//
//  1. Creating a `vfox.nu` script file in Nushell's default configuration directory. This script takes care of vfox
//     environment setup in Nushell.
//  2. Returning a short script to be added to the Nushell configuration file, which runs the `vfox.nu` script.
func (n nushell) Activate(config ActivateConfig) (string, error) {
	if len(config.Args) == 0 {
		return "", fmt.Errorf("config path is required")
	}

	// Parse and execute the template
	tmpl, err := template.New("nushell").Parse(nushellConfig)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	templateData := struct {
		SelfPath       string
		EnablePidCheck bool
	}{
		SelfPath:       config.SelfPath,
		EnablePidCheck: config.EnablePidCheck,
	}

	if err := tmpl.Execute(&buf, templateData); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	// Replace newlines for platform compatibility
	nushellConfig := strings.ReplaceAll(buf.String(), "\n", env.Newline)

	// write file to config
	targetPath := filepath.Join(config.Args[0], "vfox.nu")
	if err := os.WriteFile(targetPath, []byte(nushellConfig), 0755); err != nil {
		return "", fmt.Errorf("failed to write file: %s", err)
	}

	script := "# vfox configuration" + env.Newline +
		`source ($nu.default-config-dir | path join "vfox.nu")` + env.Newline
	return script, nil
}

// nushellExportData is used to create a JSON representation of the environment variables to be set and unset.
type nushellExportData struct {
	EnvsToSet   map[string]any `json:"envsToSet"`
	EnvsToUnset []string       `json:"envsToUnset"`
}

// Export implements shell.Export by creating a JSON representation of the environment variables to be set and unset.
// Nushell can then convert this JSON string to a [record] using the [from json] command, so it can load and unload the
// environment variables using the [load-env] and [hide-env] commands.
//
// This approach is required for Nushell because it does not support eval-like functionality. For more background
// information on this, see the article [How Nushell Code Gets Run].
//
// [record]: https://www.nushell.sh/lang-guide/chapters/types/basic_types/record.html
// [from json]: https://www.nushell.sh/commands/docs/from_json.html
// [load-env]: https://www.nushell.sh/commands/docs/load-env.html
// [hide-env]: https://www.nushell.sh/commands/docs/hide-env.html
// [How Nushell Code Gets Run]: https://www.nushell.sh/book/how_nushell_code_gets_run.html
func (n nushell) Export(envs env.Vars) string {
	exportData := nushellExportData{
		EnvsToSet:   make(map[string]any),
		EnvsToUnset: make([]string, 0),
	}

	for key, value := range envs {
		if strings.ToLower(key) == "path" {
			n.addPathToExportData(&exportData, value)
		} else {
			n.addEnvVarToExportData(&exportData, key, value)
		}
	}

	exportJson, err := json.Marshal(exportData)
	if err != nil {
		fmt.Printf("Failed to marshal export data: %s\n", err)
		return ""
	}

	return string(exportJson)
}

// addEnvVarToExportData adds an environment variable to the export data. If the value of the environment variable is
// nil, it is added as an environment variable to be unset. Otherwise, it is added as an environment variable to be set.
func (n nushell) addEnvVarToExportData(exportData *nushellExportData, envName string, value *string) {
	if value == nil {
		exportData.EnvsToUnset = append(exportData.EnvsToUnset, envName)
	} else {
		exportData.EnvsToSet[envName] = *value
	}
}

// addPathToExportData adds the PATH environment variable to the export data. Since Nushell stores the PATH as a list,
// it is first converted from a string to a list.
//
// Note: Because of the Nushell issue described at https://github.com/nushell/nushell/issues/15170, the PATH needs to be
// set as "Path" on Windows but as "PATH" on other platforms. This is the reason for using the OS-specific
// env.PathVarName constant here.
func (n nushell) addPathToExportData(exportData *nushellExportData, path *string) {
	if path == nil {
		path = new(string)
	}
	pathEntries := filepath.SplitList(*path)
	exportData.EnvsToSet[env.PathVarName] = pathEntries
}
